name: Build ANGLE

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  update-build-environment-cache:
    permissions:
      actions: write
    runs-on: ubuntu-24.04
    steps:
      - name: Restore environment from cache
        id: cached-environment-restore
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: ios_and_android-build-environment
      - name: Verify cached environment is valid
        run: |
          if [ ! -d "depot_tools" ] ; then
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          fi
          export PATH="$PWD/depot_tools:$PATH"
          gclient config --spec 'solutions = [
            {
              "name": ".",
              "url": "https://chromium.googlesource.com/angle/angle.git",
              "deps_file": "DEPS",
              "managed": False,
              "custom_vars": {},
            },
          ]
          target_os = ["ios", "android"]'
          gclient sync -Rf --no-history --with_branch_heads
# Stupid workaround, see https://github.com/azu/github-actions-overwrite-cache-example and https://github.com/actions/cache/issues/342
      - name: Delete Previous Cache
        run: |
          gh cache delete "${{ steps.cached-environment-restore.outputs.cache-primary-key }}" --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save environment to cache
        uses: actions/cache/save@v4
        with:
          path: ./
          key: ios_and_android-build-environment

  build:
    needs: update-build-environment-cache
    strategy:
      matrix:
        include:
          - os: android
            arch: arm64
            runs-on: ubuntu-24.04
          - os: android
            arch: arm
            runs-on: ubuntu-24.04
          - os: android
            arch: x86
            runs-on: ubuntu-24.04
          - os: android
            arch: x64
            runs-on: ubuntu-24.04
          - os: ios
            arch: arm64
            runs-on: macos-15
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore environment from cache
        id: cached-environment-restore
        uses: actions/cache/restore@v4
        with:
          path: ./
          key: ios_and_android-build-environment
      - name: Fetch, verify, and setup build environment
        run: |
          export PATH="$PWD/depot_tools:$PATH"
          echo "$PWD/depot_tools" >> $GITHUB_PATH
          gclient config --spec 'solutions = [
            {
              "name": ".",
              "url": "https://chromium.googlesource.com/angle/angle.git",
              "deps_file": "DEPS",
              "managed": False,
              "custom_vars": {},
            },
          ]
          target_os = ["${{ matrix.os }}"]'
          gclient sync -Rf --no-history --with_branch_heads
      - name: Build ANGLE
        run: |
          gn gen out/${{ matrix.os }}-${{ matrix.arch }}
          autoninja -C out/${{ matrix.os }}-${{ matrix.arch }}
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: ANGLE-${{ matrix.os }}-${{ matrix.arch }}
          path: out/${{ matrix.os }}-${{ matrix.arch }}
      - name: Upload shared library
        uses: actions/upload-artifact@v4
        with:
          name: ANGLE-${{ matrix.os }}-${{ matrix.arch }}.so
          path: |
            out/${{ matrix.os }}-${{ matrix.arch }}/lib*.so
            !out/${{ matrix.os }}-${{ matrix.arch }}/*.so.TOC
